name: en_file_uploader
description: This Dart package provides a file upload functionality that is implementation-agnostic. Provides the capability to upload a file in chunks with built-in retry handling.
version: 1.0.1
homepage: https://mattiapispisa.github.io/
repository: https://github.com/MattiaPispisa/file_uploader
topics: [file, upload, chunks, retry]

environment:
  sdk: ">=2.18.0 <4.0.0"

dev_dependencies:
  test: ^1.25.2
  very_good_analysis: ^5.1.0
