name: file_uploader_workspace
repository: https://github.com/MattiaPispisa/file_uploader

sdkPath: .fvm/flutter_sdk

packages:
  - "en_file_uploader"
  - "flutter_file_uploader"
  - "plugins/*"
  - "tools/*"

command:
  publish:
    hooks:
      pre: melos format && melos run analyze && melos run test

scripts:
  test:
    name: Test
    description: Run the tests
    run: dart test
    exec:
      concurrency: 1
  analyze:
    name: Analyze
    description: Analyze the code
    run: dart analyze --fatal-infos --fatal-warnings
    exec:
      concurrency: 1