name: file_uploader_workspace
homepage: https://mattiapispisa.github.io/
repository: https://github.com/MattiaPispisa/file_uploader
topics: [file, upload, chunks, retry]

environment:
  sdk: ">=2.18.0 <4.0.0"

dev_dependencies:
  melos: 6.0.0
