name: example
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  en_file_uploader: ^2.0.0
  file_uploader_socket_interfaces:
    path: ../
  file_uploader_utils: 
    path: ../../file_uploader_utils
