name: file_uploader_utils
description: common test/example utils for file uploader packages
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  en_file_uploader: "^2.0.0"

dev_dependencies:
  test: ^1.25.2
  very_good_analysis: ^5.1.0
