name: flutter_file_uploader
description: Flutter widgets that simplify the creation and use of the en_file_uploader library. They include both the UI and business logic for file management.
version: 0.1.0
publish_to: none
topics: [en_file_uploader, file, upload, widgets]

environment:
  sdk: "^3.3.0"
  flutter: "^3.19.0"

dependencies:
  flutter:
    sdk: flutter
  mobkit_dashed_border: ^0.0.6
  en_file_uploader: ^1.1.0
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0
