name: flutter_file_uploader
description: Flutter widgets that simplify the creation and use of the en_file_uploader library. They include both the UI and business logic for file management.
version: 0.1.0
publish_to: none

environment:
  sdk: "^3.3.0"
  flutter: "^3.19.0"

dependencies:
  flutter:
    sdk: flutter
  mobkit_dashed_border: ^0.0.6
  en_file_uploader:
    path: ../en_file_uploader
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0
