name: flutter_file_uploader
description: Flutter widgets that simplify the creation and use of the en_file_uploader library. They include both the UI and business logic for file management.
version: 1.3.0
topics: [file, upload, widgets, en-file-uploader]
homepage: https://mattiapispisa.github.io/
repository: https://github.com/MattiaPispisa/file_uploader/tree/main/flutter_file_uploader

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  en_file_uploader: ^2.0.0
  flutter:
    sdk: flutter
  mobkit_dashed_border: ^0.0.6
  provider: ^6.0.0

dev_dependencies:
  file_uploader_utils:
    path: ../tools/file_uploader_utils
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  test: ^1.25.5
  very_good_analysis: ^5.1.0
